# Site settings
title:          x86Sec
description:    "A security blog focusing on low-level concepts such as operating systems, reverse engineering, and binary exploitation."
baseurl:        ""
url:            "https://x86sec.com"

# Author
author:
  name:         Grant Foudree
  url:          https://x86sec.com
  email:        gfoudree@protonmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale