title: x86Sec
markdown: kramdown
url: "https://x86sec.com"
baseurl: ""
description: "A security blog focusing on low-level concepts such as operating systems, reverse engineering, and binary exploitation."

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name:         Grant Foudree
  url:          https://x86sec.com
  email:        gfoudree@protonmail.com

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
